[package]
name = "nzsc2p_json_interface"
version = "0.1.0"
authors = ["Kyle Lin <kylejlin.us@gmail.com>"]

description = "A JSON-string wrapper for nzsc2p."
repository = "https://github.com/nzsc-org/nzsc2p_json_interface"
license = "MIT"

[dependencies]
nzsc2p = "0.2.0"
